import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Pencil, Trash2, Plus } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My first Next webApp!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" flex justify-center items-center h-24 bg-blue-400">
          <h1 className="text-6xl text-center text-white font-bold ">To do List</h1>
        </div>
        <div className="flex ">
          <div className="flex flex-col  bg-blue-100 w-[150px] sm:w-60 min-h-[calc(100vh-6rem)] gap-6 p-2 pt-4 sm:p-4 sm:text-2xl">
            <h1 className= "flex justify-center items-center text-slate-700 text-center font-bold rounded-full bg-blue-400 w-[80px] sm:w-32 ">Projects:</h1>
           
            <div className="flex gap-6 sm:gap-20 justify-between items-center">
            <p>Mock</p>
                <div className="flex gap-4">
                <Pencil size={24} className="text-blue-500 hover:cursor-pointer hover:text-blue-600" />
                <Trash2 size={24} className="text-red-500 hover:cursor-pointer hover:text-red-600" />
                </div>
            </div>
         <div className="flex  justify-between items-center">
         <h1 className="text-slate-700 text-center font-bold rounded-full bg-blue-400 w-[110px] sm:w-40">New project</h1>
         <Plus size={24} className="text-blue-500 hover:cursor-pointer hover:text-blue-600" />
         </div>
          </div>
          {children}
        </div>
        
      </body>
    </html>
  );
}
